FROM ubuntu:22.04

RUN apt update && apt install -y \
    xfce4 xfce4-goodies \
    firefox \
    chromium-browser \
    novnc \
    websockify \
    x11-apps \
    dbus-x11 \
    sudo \
    wget \
    curl \
    git \
    nano \
    locales \
    && locale-gen en_US.UTF-8
