FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt update && apt install -y \
    xfce4 xfce4-goodies \
    tigervnc-standalone-server \
    novnc \
    websockify \
    x11-apps \
    dbus-x11 \
    firefox \
    chromium-browser \
    curl \
    wget \
    git \
    nano \
    locales && \
    locale-gen en_US.UTF-8
